### ISSUE TITLE
Robustness Test Info

### ISSUE THREAD

**Issue by antoalli** [zztianzz/PF-Net-Point-Fractal-Network#11]
Hi! First of all, thanks for the awesome work.
I was wondering which is the training configuration used for the robustness test on the Airplanes (Paper, Figure 9).
From my code understanding, in general, at training time you choose one viewpoint and crop points around to get the input_cropped1 shape and the respective completion GT...
Do I have to change the training procedure in order to be robust also in case of multiple holes around random positions?
If I have correctly understood, in fig 9 you're selecting two viewpoints and cropping around instead of only one, so I immagine that you also have to re-train the model coinstraining your network to output the correct number of missing points (crop_point_num * 2).
Last question, for this experiment did you train jointly on all classes or just on 'Airplane'?
Thank you very much in advance :)

**Comment by zztianzz** [comment]
Yes ， i only upload the code to generate "one viewpoint cropped" point cloud. You can change the crop strategy yourself in train.py line170-line181 and def distance_squre(like missing half of the point cloud but not a hole).  And it also need to retrain the model to get the result of fig 9.  We train jointly on several types which have max numbers of  point clouds in this dataset.  Since this question is not about the code, it will be closed soon. But you can still communicate with me by sending me emails.(m18826075629@163.com)Thanks for your interest in this work.

**Comment by antoalli** [comment]
Thanks a lot! I'll send you an email
